/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/model/place/bedroom.glb -t -o src/components/Bedroom.tsx 
*/

import * as THREE from 'three'
import React, { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { RigidBody } from '@react-three/rapier'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube: THREE.Mesh
    Cube001: THREE.Mesh
    Cube002: THREE.Mesh
    Cube003: THREE.Mesh
    Cube004: THREE.Mesh
    Cube005: THREE.Mesh
  }
  materials: {
    Material: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    ['Material.005']: THREE.MeshStandardMaterial
    ['Material.006']: THREE.MeshStandardMaterial
  }
}

export function Bedroom(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/model/place/bedroom.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh receiveShadow castShadow geometry={nodes.Cube.geometry} material={materials.Material} position={[1.032, 2, 0]} rotation={[-Math.PI, 0, 0]} scale={[-4.29, -2, -0.1]} />
        <mesh receiveShadow castShadow geometry={nodes.Cube001.geometry} material={materials['Material.001']} position={[1.032, 2, -7.715]} rotation={[-Math.PI, 0, 0]} scale={[-4.29, -2, -0.1]} />
        <mesh receiveShadow castShadow geometry={nodes.Cube002.geometry} material={materials['Material.002']} position={[-3.171, 2, -3.894]} rotation={[Math.PI, -Math.PI / 2, 0]} scale={[-3.822, -2.005, -0.133]} />
        <mesh receiveShadow castShadow geometry={nodes.Cube003.geometry} material={materials['Material.003']} position={[5.292, 2, -3.894]} rotation={[Math.PI, -Math.PI / 2, 0]} scale={[-3.822, -2.005, -0.133]} />
        <mesh receiveShadow castShadow geometry={nodes.Cube004.geometry} material={materials['Material.005']} position={[1.032, 4.07, -3.832]} rotation={[-Math.PI, 0, 0]} scale={[-4.29, -0.111, -3.995]} />
        <mesh receiveShadow geometry={nodes.Cube005.geometry} material={materials['Material.006']} position={[1.032, -0.007, -3.832]} rotation={[-Math.PI, 0, 0]} scale={[-4.29, -0.111, -3.995]} />
      </RigidBody>
    </group>
  )
}

useGLTF.preload('/model/place/bedroom.glb')
